//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Downtime_History_Synch_Help
    {
        public long Id { get; set; }
        public long Local_Id { get; set; }
        public Nullable<int> Error_Id { get; set; }
        public int Station { get; set; }
    }
}
