//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_Calculation_Period
    {
        public int Id { get; set; }
        public int Value { get; set; }
        public System.DateTime RefreshRate { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
    }
}
