//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lang_Defaults_old
    {
        public long id { get; set; }
        public string KEY_Id { get; set; }
        public string Default_Text { get; set; }
        public bool IsDeleted { get; set; }
    }
}
