//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLogin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LogstorOEEEntities : DbContext
    {
        public LogstorOEEEntities()
            : base("name=LogstorOEEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Downtime_History> Downtime_History { get; set; }
        public virtual DbSet<Downtime_Shift_History> Downtime_Shift_History { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<iFIX_Tag> iFIX_Tag { get; set; }
        public virtual DbSet<KPI> KPIs { get; set; }
        public virtual DbSet<KPI_Calc_Type_Config> KPI_Calc_Type_Config { get; set; }
        public virtual DbSet<KPI_Calculation_Period> KPI_Calculation_Period { get; set; }
        public virtual DbSet<KPI_Calculation_Type> KPI_Calculation_Type { get; set; }
        public virtual DbSet<KPI_History> KPI_History { get; set; }
        public virtual DbSet<KPI_PU_Current_Summary> KPI_PU_Current_Summary { get; set; }
        public virtual DbSet<Lang_Defaults_old> Lang_Defaults_old { get; set; }
        public virtual DbSet<Lang_Text_old> Lang_Text_old { get; set; }
        public virtual DbSet<Prod_Unit_KPI> Prod_Unit_KPI { get; set; }
        public virtual DbSet<Prod_Unit_KPI_CT> Prod_Unit_KPI_CT { get; set; }
        public virtual DbSet<Prod_Unit_Shift> Prod_Unit_Shift { get; set; }
        public virtual DbSet<Prod_Unit_Tree> Prod_Unit_Tree { get; set; }
        public virtual DbSet<Prod_Unit_Tree_Config> Prod_Unit_Tree_Config { get; set; }
        public virtual DbSet<Production_Unit> Production_Unit { get; set; }
        public virtual DbSet<Production_Unit_Type> Production_Unit_Type { get; set; }
        public virtual DbSet<Reason> Reasons { get; set; }
        public virtual DbSet<Reason_Tree> Reason_Tree { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<Shift_Excluded_Interval_History> Shift_Excluded_Interval_History { get; set; }
        public virtual DbSet<Shift_Excluded_Interval_Type> Shift_Excluded_Interval_Type { get; set; }
        public virtual DbSet<Shift_History> Shift_History { get; set; }
        public virtual DbSet<Tree_Cause_Config> Tree_Cause_Config { get; set; }
        public virtual DbSet<Tree_Cause_Dependence> Tree_Cause_Dependence { get; set; }
        public virtual DbSet<Tree_Level> Tree_Level { get; set; }
        public virtual DbSet<Tree_Type> Tree_Type { get; set; }
        public virtual DbSet<Validation_History> Validation_History { get; set; }
        public virtual DbSet<Week_Day> Week_Day { get; set; }
        public virtual DbSet<Downtime_History_Synch_Help> Downtime_History_Synch_Help { get; set; }
        public virtual DbSet<Errors_old> Errors_old { get; set; }
        public virtual DbSet<ViewDowntimeLevel> ViewDowntimeLevels { get; set; }
        public virtual DbSet<ViewDowntimeReasonTree> ViewDowntimeReasonTrees { get; set; }
        public virtual DbSet<ViewKPI> ViewKPIs { get; set; }
        public virtual DbSet<ViewKPIHistory> ViewKPIHistories { get; set; }
        public virtual DbSet<ViewProductionUnitTag> ViewProductionUnitTags { get; set; }
        public virtual DbSet<ViewProdUnitDowntTree> ViewProdUnitDowntTrees { get; set; }
        public virtual DbSet<ViewProdUnitKPI> ViewProdUnitKPIs { get; set; }
        public virtual DbSet<ViewProdUnitShift> ViewProdUnitShifts { get; set; }
        public virtual DbSet<ViewProdUnitShiftManagement> ViewProdUnitShiftManagements { get; set; }
        public virtual DbSet<ViewReason> ViewReasons { get; set; }
        public virtual DbSet<ViewReasonTree> ViewReasonTrees { get; set; }
        public virtual DbSet<ViewShift> ViewShifts { get; set; }
        public virtual DbSet<ViewShiftOnProdUnit> ViewShiftOnProdUnits { get; set; }
        public virtual DbSet<ViewTag> ViewTags { get; set; }
        public virtual DbSet<Users_Security> Users_Security { get; set; }
        public virtual DbSet<Waste_History> Waste_History { get; set; }
    
        [DbFunction("LogstorOEEEntities", "fn_Local_SplitString")]
        public virtual IQueryable<fn_Local_SplitString_Result> fn_Local_SplitString(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Local_SplitString_Result>("[LogstorOEEEntities].[fn_Local_SplitString](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        public virtual int sp_Local_AutoFillSH(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<System.DateTime> startDate, Nullable<int> daysAhead)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var daysAheadParameter = daysAhead.HasValue ?
                new ObjectParameter("DaysAhead", daysAhead) :
                new ObjectParameter("DaysAhead", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_AutoFillSH", faultComment, affectedRows, startDateParameter, daysAheadParameter);
        }
    
        public virtual int sp_Local_CalcTimeToShiftEnd(ObjectParameter faultComment, ObjectParameter timeleft, Nullable<System.DateTime> now, string tag)
        {
            var nowParameter = now.HasValue ?
                new ObjectParameter("Now", now) :
                new ObjectParameter("Now", typeof(System.DateTime));
    
            var tagParameter = tag != null ?
                new ObjectParameter("Tag", tag) :
                new ObjectParameter("Tag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_CalcTimeToShiftEnd", faultComment, timeleft, nowParameter, tagParameter);
        }
    
        public virtual int sp_Local_CalculateKpis(ObjectParameter faultComment, ObjectParameter affectedRows, string tag_Name, Nullable<int> productCount, Nullable<bool> currentProduct, Nullable<bool> currentShift)
        {
            var tag_NameParameter = tag_Name != null ?
                new ObjectParameter("Tag_Name", tag_Name) :
                new ObjectParameter("Tag_Name", typeof(string));
    
            var productCountParameter = productCount.HasValue ?
                new ObjectParameter("ProductCount", productCount) :
                new ObjectParameter("ProductCount", typeof(int));
    
            var currentProductParameter = currentProduct.HasValue ?
                new ObjectParameter("CurrentProduct", currentProduct) :
                new ObjectParameter("CurrentProduct", typeof(bool));
    
            var currentShiftParameter = currentShift.HasValue ?
                new ObjectParameter("CurrentShift", currentShift) :
                new ObjectParameter("CurrentShift", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_CalculateKpis", faultComment, affectedRows, tag_NameParameter, productCountParameter, currentProductParameter, currentShiftParameter);
        }
    
        public virtual int sp_Local_CalculateKpisWithIds(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<int> pU_Id, Nullable<int> productCount, Nullable<System.DateTime> timeStamp, Nullable<System.DateTime> endTime)
        {
            var pU_IdParameter = pU_Id.HasValue ?
                new ObjectParameter("PU_Id", pU_Id) :
                new ObjectParameter("PU_Id", typeof(int));
    
            var productCountParameter = productCount.HasValue ?
                new ObjectParameter("ProductCount", productCount) :
                new ObjectParameter("ProductCount", typeof(int));
    
            var timeStampParameter = timeStamp.HasValue ?
                new ObjectParameter("TimeStamp", timeStamp) :
                new ObjectParameter("TimeStamp", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_CalculateKpisWithIds", faultComment, affectedRows, pU_IdParameter, productCountParameter, timeStampParameter, endTimeParameter);
        }
    
        public virtual int sp_Local_Create_Holiday_Config()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_Create_Holiday_Config");
        }
    
        public virtual int sp_Local_Create_Initial_Config()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_Create_Initial_Config");
        }
    
        public virtual int sp_Local_FindShift(ObjectParameter sH_Id, Nullable<System.DateTime> time, Nullable<int> pU_Id)
        {
            var timeParameter = time.HasValue ?
                new ObjectParameter("Time", time) :
                new ObjectParameter("Time", typeof(System.DateTime));
    
            var pU_IdParameter = pU_Id.HasValue ?
                new ObjectParameter("PU_Id", pU_Id) :
                new ObjectParameter("PU_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_FindShift", sH_Id, timeParameter, pU_IdParameter);
        }
    
        public virtual int sp_Local_InsertCurrentShifts(ObjectParameter faultComment, ObjectParameter affectedRows)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_InsertCurrentShifts", faultComment, affectedRows);
        }
    
        public virtual int sp_Local_InsertNewShiftToSH(ObjectParameter faultComment, ObjectParameter affectedRows, string tagName, Nullable<System.DateTime> switchTime, Nullable<int> productCount)
        {
            var tagNameParameter = tagName != null ?
                new ObjectParameter("TagName", tagName) :
                new ObjectParameter("TagName", typeof(string));
    
            var switchTimeParameter = switchTime.HasValue ?
                new ObjectParameter("SwitchTime", switchTime) :
                new ObjectParameter("SwitchTime", typeof(System.DateTime));
    
            var productCountParameter = productCount.HasValue ?
                new ObjectParameter("ProductCount", productCount) :
                new ObjectParameter("ProductCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_InsertNewShiftToSH", faultComment, affectedRows, tagNameParameter, switchTimeParameter, productCountParameter);
        }
    
        public virtual int sp_Local_InsUpdDowntime(ObjectParameter faultComment, ObjectParameter affectedRows, ObjectParameter id, string tag_Name, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<long> downtimeValue)
        {
            var tag_NameParameter = tag_Name != null ?
                new ObjectParameter("Tag_Name", tag_Name) :
                new ObjectParameter("Tag_Name", typeof(string));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            var downtimeValueParameter = downtimeValue.HasValue ?
                new ObjectParameter("DowntimeValue", downtimeValue) :
                new ObjectParameter("DowntimeValue", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_InsUpdDowntime", faultComment, affectedRows, id, tag_NameParameter, startTimeParameter, endTimeParameter, downtimeValueParameter);
        }
    
        public virtual int sp_Local_InsUpdProdUnitShift(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<int> s_Id, Nullable<int> pU_Id, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<int> value)
        {
            var s_IdParameter = s_Id.HasValue ?
                new ObjectParameter("S_Id", s_Id) :
                new ObjectParameter("S_Id", typeof(int));
    
            var pU_IdParameter = pU_Id.HasValue ?
                new ObjectParameter("PU_Id", pU_Id) :
                new ObjectParameter("PU_Id", typeof(int));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            var valueParameter = value.HasValue ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_InsUpdProdUnitShift", faultComment, affectedRows, s_IdParameter, pU_IdParameter, startTimeParameter, endTimeParameter, valueParameter);
        }
    
        public virtual int sp_Local_InsUpdReasonsTree(ObjectParameter faultComment, ObjectParameter affectedRows, string rawInput)
        {
            var rawInputParameter = rawInput != null ?
                new ObjectParameter("RawInput", rawInput) :
                new ObjectParameter("RawInput", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_InsUpdReasonsTree", faultComment, affectedRows, rawInputParameter);
        }
    
        public virtual int sp_Local_InsUpdShift(ObjectParameter faultComment, ObjectParameter affectedRows, ObjectParameter id, string name, string description, Nullable<System.DateTime> nomStartTime, Nullable<System.DateTime> nomEndTime, Nullable<int> nomValue)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var nomStartTimeParameter = nomStartTime.HasValue ?
                new ObjectParameter("NomStartTime", nomStartTime) :
                new ObjectParameter("NomStartTime", typeof(System.DateTime));
    
            var nomEndTimeParameter = nomEndTime.HasValue ?
                new ObjectParameter("NomEndTime", nomEndTime) :
                new ObjectParameter("NomEndTime", typeof(System.DateTime));
    
            var nomValueParameter = nomValue.HasValue ?
                new ObjectParameter("NomValue", nomValue) :
                new ObjectParameter("NomValue", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_InsUpdShift", faultComment, affectedRows, id, nameParameter, descriptionParameter, nomStartTimeParameter, nomEndTimeParameter, nomValueParameter);
        }
    
        public virtual int sp_Local_InsUpdTag(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<int> id, Nullable<int> pU_Id, string name, string description)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var pU_IdParameter = pU_Id.HasValue ?
                new ObjectParameter("PU_Id", pU_Id) :
                new ObjectParameter("PU_Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_InsUpdTag", faultComment, affectedRows, idParameter, pU_IdParameter, nameParameter, descriptionParameter);
        }
    
        public virtual int sp_Local_InsUpdWorker(ObjectParameter faultComment, ObjectParameter affectedRows, ObjectParameter id, Nullable<int> o_Id, Nullable<int> pinCode, string name, string surname, string email, Nullable<bool> isOperator, Nullable<bool> isLeader, Nullable<bool> isAdmin, Nullable<bool> isAvaliable)
        {
            var o_IdParameter = o_Id.HasValue ?
                new ObjectParameter("O_Id", o_Id) :
                new ObjectParameter("O_Id", typeof(int));
    
            var pinCodeParameter = pinCode.HasValue ?
                new ObjectParameter("PinCode", pinCode) :
                new ObjectParameter("PinCode", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("Surname", surname) :
                new ObjectParameter("Surname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var isOperatorParameter = isOperator.HasValue ?
                new ObjectParameter("IsOperator", isOperator) :
                new ObjectParameter("IsOperator", typeof(bool));
    
            var isLeaderParameter = isLeader.HasValue ?
                new ObjectParameter("IsLeader", isLeader) :
                new ObjectParameter("IsLeader", typeof(bool));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("IsAdmin", isAdmin) :
                new ObjectParameter("IsAdmin", typeof(bool));
    
            var isAvaliableParameter = isAvaliable.HasValue ?
                new ObjectParameter("IsAvaliable", isAvaliable) :
                new ObjectParameter("IsAvaliable", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_InsUpdWorker", faultComment, affectedRows, id, o_IdParameter, pinCodeParameter, nameParameter, surnameParameter, emailParameter, isOperatorParameter, isLeaderParameter, isAdminParameter, isAvaliableParameter);
        }
    
        public virtual int sp_Local_KPI_3(Nullable<int> prodUnit_Id, Nullable<int> prodChangeHist_Id, Nullable<int> shiftHist_Id, Nullable<System.DateTime> productionTimeEndTime)
        {
            var prodUnit_IdParameter = prodUnit_Id.HasValue ?
                new ObjectParameter("ProdUnit_Id", prodUnit_Id) :
                new ObjectParameter("ProdUnit_Id", typeof(int));
    
            var prodChangeHist_IdParameter = prodChangeHist_Id.HasValue ?
                new ObjectParameter("ProdChangeHist_Id", prodChangeHist_Id) :
                new ObjectParameter("ProdChangeHist_Id", typeof(int));
    
            var shiftHist_IdParameter = shiftHist_Id.HasValue ?
                new ObjectParameter("ShiftHist_Id", shiftHist_Id) :
                new ObjectParameter("ShiftHist_Id", typeof(int));
    
            var productionTimeEndTimeParameter = productionTimeEndTime.HasValue ?
                new ObjectParameter("ProductionTimeEndTime", productionTimeEndTime) :
                new ObjectParameter("ProductionTimeEndTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_KPI_3", prodUnit_IdParameter, prodChangeHist_IdParameter, shiftHist_IdParameter, productionTimeEndTimeParameter);
        }
    
        public virtual int sp_Local_RefreshKPI_PU_CS(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<System.DateTime> now)
        {
            var nowParameter = now.HasValue ?
                new ObjectParameter("Now", now) :
                new ObjectParameter("Now", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_RefreshKPI_PU_CS", faultComment, affectedRows, nowParameter);
        }
    
        public virtual int sp_Local_RefreshKPItHistory(ObjectParameter faultComment, ObjectParameter affectedRows)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_RefreshKPItHistory", faultComment, affectedRows);
        }
    
        public virtual ObjectResult<sp_Local_ReportDowntimeOnCustomProdUnit_Result> sp_Local_ReportDowntimeOnCustomProdUnit(ObjectParameter faultComment, ObjectParameter affectedRows, string pU_Ids, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime)
        {
            var pU_IdsParameter = pU_Ids != null ?
                new ObjectParameter("PU_Ids", pU_Ids) :
                new ObjectParameter("PU_Ids", typeof(string));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Local_ReportDowntimeOnCustomProdUnit_Result>("sp_Local_ReportDowntimeOnCustomProdUnit", faultComment, affectedRows, pU_IdsParameter, startTimeParameter, endTimeParameter);
        }
    
        public virtual ObjectResult<sp_Local_ReportDowntimeOnCustomProdUnitAndCustomShift_Result> sp_Local_ReportDowntimeOnCustomProdUnitAndCustomShift(ObjectParameter faultComment, ObjectParameter affectedRows, string pU_Ids, string pUS_Ids, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime)
        {
            var pU_IdsParameter = pU_Ids != null ?
                new ObjectParameter("PU_Ids", pU_Ids) :
                new ObjectParameter("PU_Ids", typeof(string));
    
            var pUS_IdsParameter = pUS_Ids != null ?
                new ObjectParameter("PUS_Ids", pUS_Ids) :
                new ObjectParameter("PUS_Ids", typeof(string));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Local_ReportDowntimeOnCustomProdUnitAndCustomShift_Result>("sp_Local_ReportDowntimeOnCustomProdUnitAndCustomShift", faultComment, affectedRows, pU_IdsParameter, pUS_IdsParameter, startTimeParameter, endTimeParameter);
        }
    
        public virtual int sp_Local_Set_IsRecalc_After_Excluded_Interval_Change(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<int> pU_Id, Nullable<int> sH_Id)
        {
            var pU_IdParameter = pU_Id.HasValue ?
                new ObjectParameter("PU_Id", pU_Id) :
                new ObjectParameter("PU_Id", typeof(int));
    
            var sH_IdParameter = sH_Id.HasValue ?
                new ObjectParameter("SH_Id", sH_Id) :
                new ObjectParameter("SH_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_Set_IsRecalc_After_Excluded_Interval_Change", faultComment, affectedRows, pU_IdParameter, sH_IdParameter);
        }
    
        public virtual int sp_Local_Set_IsRecalc_KPI_PU_Current_Summary(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<System.DateTime> now)
        {
            var nowParameter = now.HasValue ?
                new ObjectParameter("Now", now) :
                new ObjectParameter("Now", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_Set_IsRecalc_KPI_PU_Current_Summary", faultComment, affectedRows, nowParameter);
        }
    
        public virtual int sp_Local_UpdDowntimeShiftConfirm(ObjectParameter faultComment, ObjectParameter affectedRows, string dH_Ids)
        {
            var dH_IdsParameter = dH_Ids != null ?
                new ObjectParameter("DH_Ids", dH_Ids) :
                new ObjectParameter("DH_Ids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_UpdDowntimeShiftConfirm", faultComment, affectedRows, dH_IdsParameter);
        }
    
        public virtual int sp_Local_UpdDowntimeShiftReason(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<long> dH_Id, Nullable<long> pUTC_Id)
        {
            var dH_IdParameter = dH_Id.HasValue ?
                new ObjectParameter("DH_Id", dH_Id) :
                new ObjectParameter("DH_Id", typeof(long));
    
            var pUTC_IdParameter = pUTC_Id.HasValue ?
                new ObjectParameter("PUTC_Id", pUTC_Id) :
                new ObjectParameter("PUTC_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_UpdDowntimeShiftReason", faultComment, affectedRows, dH_IdParameter, pUTC_IdParameter);
        }
    
        public virtual int sp_Local_Validation(ObjectParameter faultComment, ObjectParameter affectedRows, string tag_Name, Nullable<System.DateTime> endTime, Nullable<int> productCrossRefValue, Nullable<int> o_Id, Nullable<int> amount, Nullable<bool> isDowntimeNow, Nullable<long> downtimeValue)
        {
            var tag_NameParameter = tag_Name != null ?
                new ObjectParameter("Tag_Name", tag_Name) :
                new ObjectParameter("Tag_Name", typeof(string));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            var productCrossRefValueParameter = productCrossRefValue.HasValue ?
                new ObjectParameter("ProductCrossRefValue", productCrossRefValue) :
                new ObjectParameter("ProductCrossRefValue", typeof(int));
    
            var o_IdParameter = o_Id.HasValue ?
                new ObjectParameter("O_Id", o_Id) :
                new ObjectParameter("O_Id", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(int));
    
            var isDowntimeNowParameter = isDowntimeNow.HasValue ?
                new ObjectParameter("IsDowntimeNow", isDowntimeNow) :
                new ObjectParameter("IsDowntimeNow", typeof(bool));
    
            var downtimeValueParameter = downtimeValue.HasValue ?
                new ObjectParameter("DowntimeValue", downtimeValue) :
                new ObjectParameter("DowntimeValue", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Local_Validation", faultComment, affectedRows, tag_NameParameter, endTimeParameter, productCrossRefValueParameter, o_IdParameter, amountParameter, isDowntimeNowParameter, downtimeValueParameter);
        }
    
        public virtual ObjectResult<sp_Local_ViewChildCause_Result> sp_Local_ViewChildCause(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<long> pUTC_Id)
        {
            var pUTC_IdParameter = pUTC_Id.HasValue ?
                new ObjectParameter("PUTC_Id", pUTC_Id) :
                new ObjectParameter("PUTC_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Local_ViewChildCause_Result>("sp_Local_ViewChildCause", faultComment, affectedRows, pUTC_IdParameter);
        }
    
        public virtual ObjectResult<sp_Local_ViewChildSiblingCause_Result> sp_Local_ViewChildSiblingCause(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<long> pUTC_Id)
        {
            var pUTC_IdParameter = pUTC_Id.HasValue ?
                new ObjectParameter("PUTC_Id", pUTC_Id) :
                new ObjectParameter("PUTC_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Local_ViewChildSiblingCause_Result>("sp_Local_ViewChildSiblingCause", faultComment, affectedRows, pUTC_IdParameter);
        }
    
        public virtual ObjectResult<sp_Local_ViewDowntimeOnCustomProdUnit_Result> sp_Local_ViewDowntimeOnCustomProdUnit(ObjectParameter faultComment, ObjectParameter affectedRows, string pU_Ids, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime)
        {
            var pU_IdsParameter = pU_Ids != null ?
                new ObjectParameter("PU_Ids", pU_Ids) :
                new ObjectParameter("PU_Ids", typeof(string));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Local_ViewDowntimeOnCustomProdUnit_Result>("sp_Local_ViewDowntimeOnCustomProdUnit", faultComment, affectedRows, pU_IdsParameter, startTimeParameter, endTimeParameter);
        }
    
        public virtual ObjectResult<sp_Local_ViewDowntimeOnCustomProdUnitAndCustomShift_Result> sp_Local_ViewDowntimeOnCustomProdUnitAndCustomShift(ObjectParameter faultComment, ObjectParameter affectedRows, string pU_Ids, string pUS_Ids, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime)
        {
            var pU_IdsParameter = pU_Ids != null ?
                new ObjectParameter("PU_Ids", pU_Ids) :
                new ObjectParameter("PU_Ids", typeof(string));
    
            var pUS_IdsParameter = pUS_Ids != null ?
                new ObjectParameter("PUS_Ids", pUS_Ids) :
                new ObjectParameter("PUS_Ids", typeof(string));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Local_ViewDowntimeOnCustomProdUnitAndCustomShift_Result>("sp_Local_ViewDowntimeOnCustomProdUnitAndCustomShift", faultComment, affectedRows, pU_IdsParameter, pUS_IdsParameter, startTimeParameter, endTimeParameter);
        }
    
        public virtual ObjectResult<sp_Local_ViewDowntimeOnSingleProdUnit_Result> sp_Local_ViewDowntimeOnSingleProdUnit(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<int> pU_Id, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime)
        {
            var pU_IdParameter = pU_Id.HasValue ?
                new ObjectParameter("PU_Id", pU_Id) :
                new ObjectParameter("PU_Id", typeof(int));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Local_ViewDowntimeOnSingleProdUnit_Result>("sp_Local_ViewDowntimeOnSingleProdUnit", faultComment, affectedRows, pU_IdParameter, startTimeParameter, endTimeParameter);
        }
    
        public virtual ObjectResult<sp_Local_ViewDowntimeOnSingleProdUnitAndCustomShift_Result> sp_Local_ViewDowntimeOnSingleProdUnitAndCustomShift(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<int> pU_Id, string pUS_Ids, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime)
        {
            var pU_IdParameter = pU_Id.HasValue ?
                new ObjectParameter("PU_Id", pU_Id) :
                new ObjectParameter("PU_Id", typeof(int));
    
            var pUS_IdsParameter = pUS_Ids != null ?
                new ObjectParameter("PUS_Ids", pUS_Ids) :
                new ObjectParameter("PUS_Ids", typeof(string));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Local_ViewDowntimeOnSingleProdUnitAndCustomShift_Result>("sp_Local_ViewDowntimeOnSingleProdUnitAndCustomShift", faultComment, affectedRows, pU_IdParameter, pUS_IdsParameter, startTimeParameter, endTimeParameter);
        }
    
        public virtual ObjectResult<sp_Local_ViewDowntimeOnSingleProdUnitAndSingleShift_Result> sp_Local_ViewDowntimeOnSingleProdUnitAndSingleShift(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<int> pU_Id, Nullable<long> sH_Id)
        {
            var pU_IdParameter = pU_Id.HasValue ?
                new ObjectParameter("PU_Id", pU_Id) :
                new ObjectParameter("PU_Id", typeof(int));
    
            var sH_IdParameter = sH_Id.HasValue ?
                new ObjectParameter("SH_Id", sH_Id) :
                new ObjectParameter("SH_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Local_ViewDowntimeOnSingleProdUnitAndSingleShift_Result>("sp_Local_ViewDowntimeOnSingleProdUnitAndSingleShift", faultComment, affectedRows, pU_IdParameter, sH_IdParameter);
        }
    
        public virtual ObjectResult<sp_Local_ViewReasonTrees_Result> sp_Local_ViewReasonTrees(ObjectParameter faultComment, ObjectParameter affectedRows, string treeType, Nullable<int> treeId)
        {
            var treeTypeParameter = treeType != null ?
                new ObjectParameter("TreeType", treeType) :
                new ObjectParameter("TreeType", typeof(string));
    
            var treeIdParameter = treeId.HasValue ?
                new ObjectParameter("TreeId", treeId) :
                new ObjectParameter("TreeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Local_ViewReasonTrees_Result>("sp_Local_ViewReasonTrees", faultComment, affectedRows, treeTypeParameter, treeIdParameter);
        }
    
        public virtual ObjectResult<sp_Local_ViewShiftListOnCustomProdUnit_Result> sp_Local_ViewShiftListOnCustomProdUnit(ObjectParameter faultComment, ObjectParameter affectedRows, string pU_Ids)
        {
            var pU_IdsParameter = pU_Ids != null ?
                new ObjectParameter("PU_Ids", pU_Ids) :
                new ObjectParameter("PU_Ids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Local_ViewShiftListOnCustomProdUnit_Result>("sp_Local_ViewShiftListOnCustomProdUnit", faultComment, affectedRows, pU_IdsParameter);
        }
    
        public virtual ObjectResult<sp_Local_ViewShiftListOnSingleProdUnit_Result> sp_Local_ViewShiftListOnSingleProdUnit(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<int> pU_Id)
        {
            var pU_IdParameter = pU_Id.HasValue ?
                new ObjectParameter("PU_Id", pU_Id) :
                new ObjectParameter("PU_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Local_ViewShiftListOnSingleProdUnit_Result>("sp_Local_ViewShiftListOnSingleProdUnit", faultComment, affectedRows, pU_IdParameter);
        }
    
        public virtual ObjectResult<sp_Local_ViewSingleDowntimeConfig_Result> sp_Local_ViewSingleDowntimeConfig(ObjectParameter faultComment, ObjectParameter affectedRows, Nullable<long> dH_Id)
        {
            var dH_IdParameter = dH_Id.HasValue ?
                new ObjectParameter("DH_Id", dH_Id) :
                new ObjectParameter("DH_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Local_ViewSingleDowntimeConfig_Result>("sp_Local_ViewSingleDowntimeConfig", faultComment, affectedRows, dH_IdParameter);
        }
    
        public virtual int SynchronizeDowntime()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SynchronizeDowntime");
        }
    }
}
