//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_Unit_Tree_Config
    {
        public int Id { get; set; }
        public int PUT_Id { get; set; }
        public long TCC_Id { get; set; }
        public Nullable<int> CrossRefValue { get; set; }
        public int TT_Id { get; set; }
        public bool IsPlanned { get; set; }
        public bool IsDeleted { get; set; }
    }
}
