//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift_History
    {
        public long Id { get; set; }
        public int PU_Id { get; set; }
        public int PUS_Id { get; set; }
        public int SEIT_Id { get; set; }
        public int WD_Id { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool IsHoliday { get; set; }
        public Nullable<bool> IsRecalc { get; set; }
        public bool IsSynch { get; set; }
    }
}
