//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NamePL { get; set; }
        public string DescriptionPL { get; set; }
        public System.DateTime NomStartTime { get; set; }
        public System.DateTime NomEndTime { get; set; }
        public int NomValue { get; set; }
        public bool IsDeleted { get; set; }
    }
}
