//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tree_Cause_Config
    {
        public long Id { get; set; }
        public int RT_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NamePL { get; set; }
        public string DescriptionPL { get; set; }
        public Nullable<int> NomCrossRefValue { get; set; }
        public bool NomIsPlanned { get; set; }
        public int TT_Id { get; set; }
        public bool IsDeleted { get; set; }
    }
}
