//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tree_Cause_Dependence
    {
        public long Id { get; set; }
        public Nullable<long> MTCD_Id { get; set; }
        public int RT_Id { get; set; }
        public long TCC_Id { get; set; }
        public Nullable<int> TL_Id { get; set; }
        public int TT_Id { get; set; }
    }
}
