//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Validation_History
    {
        public int Id { get; set; }
        public int PU_Id { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<int> SLH_Id { get; set; }
        public Nullable<int> PCH_Id { get; set; }
        public Nullable<int> SH_Id { get; set; }
        public Nullable<int> PCSH_Id { get; set; }
        public Nullable<int> O_Id { get; set; }
        public Nullable<int> OH_Id { get; set; }
        public Nullable<int> DH_Id { get; set; }
        public Nullable<int> DPH_Id { get; set; }
        public Nullable<int> DSH_Id { get; set; }
    }
}
