//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProductionUnitTag
    {
        public int Id { get; set; }
        public int UnitId { get; set; }
        public string TagName { get; set; }
        public string UnitName { get; set; }
        public string TagDesc { get; set; }
        public string UnitDesc { get; set; }
    }
}
