//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waste_History
    {
        public long Id { get; set; }
        public int PU_Id { get; set; }
        public Nullable<int> PUP_Id { get; set; }
        public Nullable<int> PUS_Id { get; set; }
        public Nullable<int> PUW_Id { get; set; }
        public Nullable<int> C_Id { get; set; }
        public Nullable<int> PCH_Id { get; set; }
        public Nullable<int> SH_Id { get; set; }
        public Nullable<double> Amount { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool isConfirmed { get; set; }
        public bool isDeleted { get; set; }
    }
}
